export const fakeImage = "https://placehold.co/600x400";

export const InterestInfo = {
  selfCare: [
    "Aromatherapy",
    "Astrology",
    "Cold plunging",
    "Crystals",
    "Deep chats",
    "Journaling",
    "Mindfulness",
    "Nutrition",
    "Retreats",
    "Skin care",
    "Sleeping well",
    "Slow living",
    "Therapy",
    "Time offline",
    "Meditation",
  ],
  sports: [
    "Football",
    "Basketball",
    "Tennis",
    "Swimming",
    "Soccer",
    "Baseball",
    "Volleyball",
    "Running",
    "Cycling",
    "Hiking",
    "Yoga",
    "Pilates",
    "Weightlifting",
    "Rock Climbing",
    "Surfing",
  ],
  pets: [
    "Dogs",
    "Cats",
    "Birds",
    "Rabbits",
    "Hamsters",
    "Guinea Pigs",
    "Fish",
    "Reptiles",
    "Turtles",
    "Horses",
    "Ferrets",
    "Chinchillas",
    "Gerbils",
    "Mice",
    "Rats",
  ],
  valuesAndAllyship: [
    "Equality",
    "Inclusivity",
    "Diversity",
    "Sustainability",
    "Social Justice",
    "Human Rights",
    "Animal Rights",
    "Environmentalism",
    "Volunteerism",
    "Community Support",
    "Empathy",
    "Respect",
    "Integrity",
    "Kindness",
    "Fairness",
  ],
  filmAndTV: [
    "Action",
    "Comedy",
    "Drama",
    "Sci-Fi",
    "Fantasy",
    "Horror",
    "Thriller",
    "Documentary",
    "Animation",
    "Romance",
    "Crime",
    "Mystery",
    "Historical",
    "Musical",
    "Reality TV",
  ],
  personalityAndTraits: [
    "Introverted",
    "Extroverted",
    "Ambitious",
    "Creative",
    "Analytical",
    "Empathetic",
    "Optimistic",
    "Pessimistic",
    "Organized",
    "Spontaneous",
    "Patient",
    "Impatient",
    "Confident",
    "Shy",
    "Resilient",
  ],
  reading: [
    "Fiction",
    "Non-Fiction",
    "Poetry",
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Romance",
    "Historical Fiction",
    "Biography",
    "Autobiography",
    "Self-Help",
    "Travel",
    "Cookbooks",
    "Graphic Novels",
  ],
  music: [
    "Rock",
    "Jazz",
    "Classical",
    "Pop",
    "Hip-Hop",
    "Electronic",
    "Country",
    "Blues",
    "Folk",
    "Reggae",
    "Metal",
    "Indie",
    "Punk",
    "R&B",
    "Soul",
  ],
  FoodAndRinks: [
    "Italian",
    "Mexican",
    "Chinese",
    "Japanese",
    "Indian",
    "Thai",
    "French",
    "Mediterranean",
    "Vegan",
    "Vegetarian",
    "Seafood",
    "Steak",
    "Coffee",
    "Tea",
    "Wine",
  ],
  traveling: [
    "Beaches",
    "Mountains",
    "Road Trips",
    "Adventure",
    "City Breaks",
    "Cultural Tours",
    "Backpacking",
    "Cruises",
    "Hiking Trips",
    "Camping",
    "Luxury Travel",
    "Solo Travel",
    "Group Travel",
    "Ecotourism",
    "Food Tours",
  ],
  creativity: [
    "Painting",
    "Drawing",
    "Writing",
    "Sculpting",
    "Photography",
    "Music Composition",
    "Dance",
    "Acting",
    "Graphic Design",
    "Web Design",
    "Fashion Design",
    "Interior Design",
    "Crafting",
    "Cooking",
    "Filmmaking",
  ],
  goingOut: [
    "Restaurants",
    "Bars",
    "Clubs",
    "Concerts",
    "Theater",
    "Movies",
    "Sporting Events",
    "Festivals",
    "Art Galleries",
    "Museums",
    "Parks",
    "Hiking Trails",
    "Shopping",
    "Sightseeing",
    "Comedy Shows",
  ],
  stayingIn: [
    "Reading",
    "Watching Movies",
    "Playing Video Games",
    "Cooking",
    "Baking",
    "Listening to Music",
    "Relaxing Baths",
    "Meditation",
    "Yoga",
    "Crafting",
    "Online Courses",
    "Board Games",
    "Puzzles",
    "Journaling",
    "Spending Time with Family",
  ],
};

export const professions = [
  "Software Engineer",
  "Doctor",
  "Teacher",
  "Nurse",
  "Accountant",
  "Lawyer",
  "Architect",
  "Engineer",
  "Artist",
  "Writer",
  "Designer",
  "Chef",
  "Police Officer",
  "Firefighter",
  "Pilot",
  "Journalist",
  "Scientist",
  "Pharmacist",
  "Dentist",
  "Psychologist",
  "Veterinarian",
  "Electrician",
  "Plumber",
  "Mechanic",
  "Real Estate Agent",
  "Marketing Manager",
  "Sales Representative",
  "Financial Analyst",
  "HR Manager",
  "Project Manager",
  "Graphic Designer",
  "Web Developer",
  "Data Scientist",
  "Business Analyst",
  "Consultant",
  "Social Worker",
  "Photographer",
  "Musician",
  "Actor",
  "Director",
  "Producer",
  "Editor",
  "Translator",
  "Interpreter",
  "Librarian",
  "Researcher",
  "Biologist",
  "Chemist",
  "Physicist",
  "Mathematician",
  "Statistician",
  "Economist",
  "Historian",
  "Geologist",
  "Meteorologist",
  "Astronomer",
  "Zoologist",
  "Botanist",
  "Marine Biologist",
  "Environmental Scientist",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Aerospace Engineer",
  "Industrial Engineer",
  "Biomedical Engineer",
  "Nuclear Engineer",
  "Mining Engineer",
  "Petroleum Engineer",
  "Actuary",
  "Anthropologist",
  "Archaeologist",
  "Audiologist",
  "Baker",
  "Barista",
  "Bartender",
  "Beautician",
  "Biochemist",
  "Bookkeeper",
  "Carpenter",
  "Cartographer",
  "Cashier",
  "Chiropractor",
  "Clergy Member",
  "Computer Programmer",
  "Construction Worker",
  "Copywriter",
  "Counselor",
  "Courier",
  "Dancer",
  "Database Administrator",
  "Delivery Driver",
  "Dietitian",
  "DJ",
  "Drafter",
  "Econometrician",
  "Educator",
  "Entomologist",
  "Epidemiologist",
  "Event Planner",
  "Executive Assistant",
  "Farmer",
  "Fashion Designer",
  "Film Editor",
  "Florist",
  "Forensic Scientist",
  "Forester",
  "Freight Broker",
  "Game Designer",
  "Gardener",
  "Geneticist",
  "Geographer",
  "Glazier",
  "Hair Stylist",
  "Health Inspector",
  "Horticulturist",
  "Hotel Manager",
  "Hydrologist",
  "Illustrator",
  "Importer/Exporter",
  "Information Architect",
  "Insurance Agent",
  "Interior Decorator",
  "Investment Banker",
  "IT Manager",
  "Jeweler",
  "Judge",
  "Kinesiologist",
  "Landscaper",
  "Lecturer",
  "Legal Assistant",
  "Linguist",
  "Loan Officer",
  "Logistics Manager",
  "Machine Operator",
  "Mail Carrier",
  "Makeup Artist",
  "Management Analyst",
  "Manicurist",
  "Mason",
  "Massage Therapist",
  "Materials Scientist",
  "Medical Assistant",
  "Medical Biller",
  "Medical Coder",
  "Medical Lab Technician",
  "Medical Technologist",
  "Metallurgist",
  "Microbiologist",
  "Model",
  "Mortgage Broker",
  "Nail Technician",
  "Network Administrator",
  "Neuroscientist",
  "Nutritionist",
  "Occupational Therapist",
  "Oceanographer",
  "Optician",
  "Optometrist",
  "Orthodontist",
  "Painter",
  "Paleontologist",
  "Paralegal",
  "Pathologist",
  "Pediatrician",
  "Personal Trainer",
  "Pest Control Worker",
  "Pet Groomer",
  "Philologist",
  "Physical Therapist",
  "Physiologist",
  "Podiatrist",
  "Political Scientist",
  "Postal Worker",
  "PR Specialist",
  "Proofreader",
  "Property Manager",
  "Psychiatrist",
  "Public Health Worker",
  "Public Relations Manager",
  "Publisher",
  "Purchasing Manager",
  "Radiologic Technologist",
  "Receptionist",
  "Recruiter",
  "Referee",
  "Registrar",
  "Respiratory Therapist",
  "Robotics Engineer",
  "Roofer",
  "Safety Engineer",
  "Security Guard",
  "Seismologist",
  "Sign Language Interpreter",
  "Speech Pathologist",
  "Stage Manager",
  "Statistician",
  "Stockbroker",
  "Surveyor",
  "Systems Analyst",
  "Technical Writer",
  "Telecommunications Engineer",
  "Tour Guide",
  "Toxicologist",
  "Traffic Controller",
  "Training and Development Manager",
  "Travel Agent",
  "Tree Surgeon",
  "Umpire",
  "Underwriter",
  "Urban Planner",
  "UX Designer",
  "Video Editor",
  "Vocational Counselor",
  "Waiter/Waitress",
  "Welder",
  "Wildlife Biologist",
  "Woodworker",
  "Youth Worker",
  "Acupuncturist",
  "Actuary",
  "Advertising Executive",
  "Agricultural Engineer",
  "Air Traffic Controller",
  "Ambulance Driver",
  "Animal Trainer",
  "Appraiser",
  "Arbitrator",
  "Art Director",
  "Athletic Trainer",
  "Auctioneer",
  "Automotive Engineer",
  "Aviation Mechanic",
  "Ballistics Expert",
  "Bank Teller",
  "Bicycle Mechanic",
  "Bilingual Teacher",
  "Bioinformatician",
  "Blacksmith",
  "Boat Builder",
  "Bookbinder",
  "Bounty Hunter",
  "Bricklayer",
  "Broadcast Journalist",
  "Butcher",
  "Cabinetmaker",
  "Calligrapher",
  "Cameraman/Camerawoman",
  "Car Detailer",
  "Cardiologist",
  "Caretaker",
  "Casino Dealer",
  "Caterer",
  "Cell Biologist",
  "Ceramicist",
  "Choreographer",
  "Claims Adjuster",
  "Clinical Psychologist",
  "Clothing Designer",
  "Coach",
  "Commercial Pilot",
  "Commodities Broker",
  "Community Health Worker",
  "Composer",
  "Concierge",
  "Conservation Scientist",
  "Consumer Advocate",
  "Contractor",
  "Corrections Officer",
  "Cosmetologist",
  "Court Reporter",
  "Crane Operator",
  "Credit Analyst",
  "Criminal Profiler",
  "Croupier",
  "Cryptographer",
  "Curator",
  "Customs Broker",
  "Cytotechnologist",
  "Dairy Farmer",
  "Dermatologist",
  "Detective",
  "Development Officer",
  "Digital Marketing Specialist",
  "Diplomat",
  "Dispensing Optician",
  "Dog Walker",
  "Doorman",
  "Driller",
  "Driving Instructor",
  "Drug Counselor",
  "Early Childhood Educator",
  "E-commerce Manager",
  "Educational Administrator",
  "Emergency Management Specialist",
  "Endocrinologist",
  "Energy Auditor",
  "English Teacher",
  "Ergonomist",
  "Escrow Officer",
  "Estate Planner",
  "Ethicist",
  "Ethnographer",
  "Exterminator",
  "Facilities Manager",
  "Family Lawyer",
  "Fence Installer",
  "Film Producer",
  "Financial Advisor",
  "Fine Artist",
  "Fisherman",
  "Flight Attendant",
  "Food Scientist",
  "Foreign Language Teacher",
  "Foundation Manager",
  "Funeral Director",
  "Furniture Designer",
  "Futures Trader",
  "Game Developer",
  "Gemologist",
  "General Practitioner",
  "Gerontologist",
  "Glass Blower",
  "Government Contractor",
  "Grant Writer",
  "Grave Digger",
  "Green Energy Specialist",
  "Griot",
  "Groundskeeper",
  "Gynecologist",
  "Handyman",
  "Hazardous Materials Handler",
  "Health Educator",
  "Hearing Aid Specialist",
  "Heavy Equipment Operator",
  "Hedge Fund Manager",
  "Herbalist",
  "High School Teacher",
  "Home Inspector",
  "Horse Trainer",
  "Hospice Worker",
  "Housekeeper",
  "Human Resources Assistant",
  "Hypnotherapist",
  "Immigration Lawyer",
  "Immunologist",
  "Import/Export Specialist",
  "Information Security Analyst",
  "Inspector",
  "Instructional Designer",
  "Intelligence Analyst",
  "Investment Analyst",
  "Irrigation Technician",
  "IT Consultant",
  "Jailer",
  "Janitor",
  "Jewelry Designer",
  "Job Counselor",
  "Jockey",
  "Judge Advocate",
  "Kennel Worker",
  "Key Account Manager",
  "Kindergarten Teacher",
  "Kitchen Designer",
  "Knot Tier",
  "Labor Relations Specialist",
  "Land Surveyor",
  "Landlord",
  "Laser Technician",
  "Laundry Worker",
  "Law Clerk",
  "Lead Auditor",
  "Learning and Development Specialist",
  "Leasing Agent",
  "Legal Secretary",
  "Legislative Assistant",
  "Letter Carrier",
  "Life Coach",
  "Lobbyist",
  "Locksmith",
  "Longshoreman",
  "Loss Prevention Specialist",
  "Lumberjack",
  "Luxury Goods Salesperson",
  "Machinist",
  "Management Consultant",
  "Maitre D'",
  "Mall Manager",
  "Manufacturing Engineer",
  "Market Research Analyst",
  "Marriage Counselor",
  "Masseur/Masseuse",
  "Materials Engineer",
  "Meat Cutter",
  "Media Buyer",
  "Medical Illustrator",
  "Medical Transcriptionist",
  "Mental Health Counselor",
  "Merchandiser",
  "Messenger",
  "Midwife",
  "Military Officer",
  "Millwright",
  "Mine Worker",
  "Mortician",
  "Mover",
  "Multimedia Artist",
  "Museum Curator",
  "Music Producer",
  "Naval Architect",
  "Network Engineer",
  "Neurologist",
  "Newspaper Editor",
  "Notary Public",
  "Nuclear Medicine Technologist",
  "Nursery Worker",
  "Obstetrician",
  "Offshore Worker",
  "Oncologist",
  "Student",
];
